name: RemoteViewer
options:
  bundleIdPrefix: cz.helptech
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: cz.helptech.RemoteViewer
    MARKETING_VERSION: "1.2.0"
    CURRENT_PROJECT_VERSION: "3"
    DEVELOPMENT_TEAM: ""
    SWIFT_VERSION: "5.9"

targets:
  RemoteViewer:
    type: application
    platform: macOS
    sources:
      - RemoteViewer
    settings:
      base:
        INFOPLIST_FILE: RemoteViewer/Info.plist
        PRODUCT_NAME: ServiDesk Viewer
        MACOSX_DEPLOYMENT_TARGET: "13.0"
    entitlements:
      path: RemoteViewer/RemoteViewer.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.network.client: true
