name: ServiDeskAgent
options:
  bundleIdPrefix: cz.helptech
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: cz.helptech.ServiDeskAgent
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    SWIFT_VERSION: "5.9"

targets:
  ServiDeskAgent:
    type: application
    platform: macOS
    sources:
      - ServiDeskAgent
    settings:
      base:
        INFOPLIST_FILE: ServiDeskAgent/Info.plist
        PRODUCT_NAME: "ServiDesk Agent"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
    entitlements:
      path: ServiDeskAgent/ServiDeskAgent.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.network.client: true
